/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardActivityRouteImport } from './routes/_authed/dashboard/activity'
import { Route as AuthedDashboardMembersIndexRouteImport } from './routes/_authed/dashboard/members/index'
import { Route as AuthedDashboardMembersMemberIdRouteImport } from './routes/_authed/dashboard/members/$memberId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardActivityRoute = AuthedDashboardActivityRouteImport.update({
  id: '/dashboard/activity',
  path: '/dashboard/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardMembersIndexRoute =
  AuthedDashboardMembersIndexRouteImport.update({
    id: '/dashboard/members/',
    path: '/dashboard/members/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardMembersMemberIdRoute =
  AuthedDashboardMembersMemberIdRouteImport.update({
    id: '/dashboard/members/$memberId',
    path: '/dashboard/members/$memberId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/activity': typeof AuthedDashboardActivityRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/members/$memberId': typeof AuthedDashboardMembersMemberIdRoute
  '/dashboard/members/': typeof AuthedDashboardMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/activity': typeof AuthedDashboardActivityRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/members/$memberId': typeof AuthedDashboardMembersMemberIdRoute
  '/dashboard/members': typeof AuthedDashboardMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/_authed/dashboard/activity': typeof AuthedDashboardActivityRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/members/$memberId': typeof AuthedDashboardMembersMemberIdRoute
  '/_authed/dashboard/members/': typeof AuthedDashboardMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/health'
    | '/dashboard/activity'
    | '/dashboard/'
    | '/dashboard/members/$memberId'
    | '/dashboard/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/health'
    | '/dashboard/activity'
    | '/dashboard'
    | '/dashboard/members/$memberId'
    | '/dashboard/members'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authed'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/api/health'
    | '/_authed/dashboard/activity'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/members/$memberId'
    | '/_authed/dashboard/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/activity': {
      id: '/_authed/dashboard/activity'
      path: '/dashboard/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof AuthedDashboardActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/members/': {
      id: '/_authed/dashboard/members/'
      path: '/dashboard/members'
      fullPath: '/dashboard/members/'
      preLoaderRoute: typeof AuthedDashboardMembersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/members/$memberId': {
      id: '/_authed/dashboard/members/$memberId'
      path: '/dashboard/members/$memberId'
      fullPath: '/dashboard/members/$memberId'
      preLoaderRoute: typeof AuthedDashboardMembersMemberIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardActivityRoute: typeof AuthedDashboardActivityRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardMembersMemberIdRoute: typeof AuthedDashboardMembersMemberIdRoute
  AuthedDashboardMembersIndexRoute: typeof AuthedDashboardMembersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardActivityRoute: AuthedDashboardActivityRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardMembersMemberIdRoute: AuthedDashboardMembersMemberIdRoute,
  AuthedDashboardMembersIndexRoute: AuthedDashboardMembersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
